### ISSUE TITLE
`cjose_jws_import failed` when used with `mod_auth_openidc`

### ISSUE THREAD

**Issue by dhanak** [dbluhm/noauth#3]
Hi!

I'm trying to use your mock server in a docker compose setup, where my application is running in an Apache2 server. I'm using `mod_auth_openidc` to handle the OpenID Connect negotiations. I managed to get your server up and running, I get as far as receiving the token correctly, but on the receiving end, the authentication breaks down with the followin error message:

```
noauth-1       | INFO:     172.19.1.1:44344 - "POST /oidc/submit/4841858c-dba5-48aa-bbb3-e067c0f003c7 HTTP/1.1" 303 See Other
noauth-1       | INFO:     192.168.32.4:60768 - "POST /oidc/token HTTP/1.1" 200 OK
httpd-1        | [Mon Aug 05 07:35:56.569419 2024] [auth_openidc:error] [pid 13:tid 13] [client 172.19.1.1:58648] oidc_proto_validate_code_response: requested flow is "code" but no "access_token" parameter found in the code response, referer: http://docker:8081/
```

Note that in order to get this far, I had to make two changes:

1. I had to add a `[noauth] passphrase` setting to the `noauth.toml` config file, otherwise the noauth server wouldn't start;
2. A needed to add extra query parameters to the `/oidc/token` request from the Apache side, using `OIDCProviderTokenEndpointParams client_id=local&client_secret=secret`, because the noauth app requires them (even though they are probably not neccessary according to the protocol spec).

I figured out these, but I coulnd't get past the missing `access_token` issue. Any help would be appreciated!

**Comment by dhanak** [comment]
On further inspection, I succeded to add a dummy access token to the return value of `async def token()`, but that didn't improve the situation a lot. Now the process gets stuck with the following error message:

```
oauth-1       | INFO:     192.168.32.4:47486 - "POST /oidc/token HTTP/1.1" 200 OK
httpd-1        | [Mon Aug 05 15:37:09.356181 2024] [auth_openidc:debug] [pid 10:tid 10] src/util.c(1052): [client 172.19.1.1:55166] oidc_util_http_call: HTTP response code=200, referer: http://lxc-docker:8081/
httpd-1        | [Mon Aug 05 15:37:09.356195 2024] [auth_openidc:debug] [pid 10:tid 10] src/util.c(1057): [client 172.19.1.1:55166] oidc_util_http_call: response={"access_token":"token","token_type":"Bearer","expires_in":300,"scope":"openid","id_token":"eyJhbGciOiJFZERTQSIsImtpZCI6InpIMERodnFYbGVudFYtVW54VkFmcjR1VURoRUx0MWxrbG5IWFlSZFpuZTgifQ.eyJleHAiOjE3MjI4NzI1MjksImlhdCI6MTcyMjg3MjIyOSwiYXV0aF90aW1lIjoxNzIyODcyMjI5LCJqdGkiOiJhMzY1MjM4MS0zNTliLTQ0MDYtODJiOC1lMzU5NDI1NmQyNmQiLCJpc3MiOiJodHRwOi8vbHhjLWRvY2tlcjo4MDgxIiwiYXVkIjoiZXRzLWxvY2FsIiwidHlwIjoiSUQiLCJhenAiOiJldHMtbG9jYWwiLCJzdWIiOiJjMGZjNWMzMy04ZmQ2LTQ4YzktYWExMi0xMzY4NWUwM2I1MjIiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImdpdmVuX25hbWUiOiJKb2huIiwibmFtZSI6IkpvaG4iLCJuZXB0dW5fY29kZSI6IjEyMzQ1NiJ9.w5rmvy3sRtMRWh7milLnXExahUAuK1klVrMalN6mLED4MsnEHSMIGt-0d6usNas-2orYJ1fj8heeVF7AZWk4AQ"}, referer: http://lxc-docker:8081/
httpd-1        | [Mon Aug 05 15:37:09.356294 2024] [auth_openidc:debug] [pid 10:tid 10] src/proto.c(2685): [client 172.19.1.1:55166] oidc_proto_validate_code_response: enter, referer: http://lxc-docker:8081/
httpd-1        | [Mon Aug 05 15:37:09.356347 2024] [auth_openidc:debug] [pid 10:tid 10] src/proto.c(1627): [client 172.19.1.1:55166] oidc_proto_parse_idtoken: enter: id_token header={"alg":"EdDSA","kid":"zH0DhvqXlentV-UnxVAfr4uUDhELt1lklnHXYRdZne8"}, referer: http://lxc-docker:8081/
httpd-1        | [Mon Aug 05 15:37:09.356385 2024] [auth_openidc:debug] [pid 10:tid 10] src/util.c(2379): [client 172.19.1.1:55166] oidc_util_create_symmetric_key: key_len=32, referer: http://lxc-docker:8081/
httpd-1        | [Mon Aug 05 15:37:09.356420 2024] [auth_openidc:error] [pid 10:tid 10] [client 172.19.1.1:55166] oidc_proto_parse_idtoken: oidc_jwt_parse failed: [src/jose.c:813: oidc_jwt_parse]: cjose_jws_import failed: invalid argument [file: jws.c, function: cjose_jws_import, line: 834], referer: http://lxc-docker:8081/
```

Something's probably wrong with the signature verification (because it is clear that the token itself is decoded correctly), but I don't know enough about JWT tokens to understand what. That `create_symmetric_key` call seems wrong, I would expect an assymetric key to be used, but I'm really out of my depth here.

**Comment by dbluhm** [comment]
Thanks for the report! Glad to see that someone else is getting use out of NoAuth. I'll take a look at these errors and see what I can parse.

**Comment by dbluhm** [comment]
From my analysis, it looks like the error you're seeing is the result of mod_auth_openidc not supporting EdDSA signatures. I defaulted to EdDSA since this is commonly used in the spaces I work in but I think it should be straightforward to support one or more of the more commonly implemented algorithms, such as ES256.

**Comment by dbluhm** [comment]
@dhanak What value are you using for the token authentication method? (https://github.com/OpenIDC/mod_auth_openidc/blob/v2.4.15.7/auth_openidc.conf#L102-L107)

**Comment by dhanak** [comment]
Hi @dbluhm! I was using the default, which I believe is `client_secret_basic`. Since then I learned that I could have switched to `client_secret_post`, but as you can see from the issue description, I also tried adding the credentials manually to the URL by using `OIDCProviderTokenEndpointParams`, and it didn't help. Does the post method cause other differences as well?

Meanwhile, I really had to make progress, so I've switched to keycloak, which is much more complicated than noauth, but it works for now. I might return to noauth later on.

**Comment by dbluhm** [comment]
Thanks for the info and your original report! I'll close this issue as completed by #4 and have created a separate issue to document supporting more client authentication modes.
